- name: Prepare certificates
  ansible.builtin.import_tasks: certs.yml

- name: Configure docker trust
  ansible.builtin.import_tasks: docker.yml

- name: Prepare docker compose deployment
  ansible.builtin.import_tasks: dcompose.yml
