- name: Install mongodb
  ansible.builtin.import_tasks:
    file: install.yml

- name: Configure mongodb
  ansible.builtin.import_tasks:
    file: config.yml

- name: Spinup mongodb replica set
  ansible.builtin.import_tasks:
    file: spinup.yml

- name: Backup the secondary replica
  ansible.builtin.import_tasks:
    file: backup.yml
