- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install required apt packages
  ansible.builtin.apt:
    name: "{{ etc_monitor_packages }}"
    state: present
  no_log: true

- name: Make sure the postfix service is active
  ansible.builtin.systemd:
    name: postfix
    daemon_reload: true
    enabled: true
    state: started
  no_log: true

- name: Create script directory
  ansible.builtin.file:
    path: "{{ etc_monitor_dir }}"
    state: directory
    mode: "0755"

- name: Copy the monitoring script
  ansible.builtin.copy:
    src: etc-monitor.sh
    dest: "{{ etc_monitor_dir }}/etc-monitor.sh"
    mode: "0755"

- name: Install systemd service
  ansible.builtin.template:
    src: etc-monitor.service.j2
    dest: /etc/systemd/system/etc-monitor.service
    mode: "0644"

- name: Enable and start monitoring service
  ansible.builtin.systemd:
    name: etc-monitor.service
    daemon_reload: true
    enabled: true
    state: started
  no_log: true
