$ANSIBLE_VAULT;1.1;AES256
38383934666632623766636539353838613461643035633361646133626531656361396263373633
6134653861306439346561346661303562643339346532620a353565643339653433356330343264
66306435653536643431623166613038623232376635323463666535623061323539363031626630
3739393265363965370a383238383932656162303264623530363938336431633830656134353861
38646666643330306537663562356138353432333639313739333135653535303331383966373339
34303465386662623166646665316531636431363665646132626265393130373165626534663430
66633731653865363334623836393835666466656564656433646466643136366431646138386537
34383138663231626363353563646462306138336338393232386666396438336438396236373564
39623861303637336565353439333462623538323663353464356239663335343762663030616464
63383434663333306661333536663831303662343262646136623634363335383561313562383538
65383666333465343964636239333165623464663632373561343934653663363134613739326632
66336266313865653638393938393263616433346231333133646432663865646436353331356465
66366535333432636338636135613761343466643066353162323936326230623332316362623732
6130653136626631383337346366343639396636396431393430
