name: E2E Playbook Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  install-docker:
    runs-on: ubuntu-latest

    services:
      ubuntu:
        image: ubuntu:24.04
        options: >-
          --name ubuntu
          --privileged
          --interactive

    steps:
      - uses: actions/checkout@v5

      - name: List Docker containers
        run: docker ps -a

      - name: Install python in ubuntu
        run: |
          echo "# ----- install python3 ----- #"
          docker exec ubuntu apt-get -qq update
          docker exec ubuntu apt-get -qq install -y python3
          echo "# ----- inspect python ----- #"
          docker exec ubuntu which -a python3
          docker exec ubuntu python3 --version

      - uses: cachix/install-nix-action@v31

      - name: Run Ansible Playbook
        shell: nix shell nixpkgs#ansible --quiet --command bash {0}
        run: |
          ansible-inventory -i inventories/ci-containers.yml --list
          ansible-playbook -i inventories/ci-containers.yml \
            playbooks/install-docker.yml -vv
